# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 11:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Отчество не может содержать цифры', regex='^[a-zA-Zа-яА-Я\\s]+$')], verbose_name='Отчество'),
        ),
    ]
