# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_data_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_inspector',
            field=models.BooleanField(default=False, help_text='Указывает, что пользователь имеет статус инспектора и может оставлять метки.', verbose_name='Статус инспектора'),
        ),
    ]
