# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181115_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_inspector',
            field=models.BooleanField(default=False, verbose_name='Статус инспектора'),
        ),
    ]
