# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181115_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Прописка'),
        ),
    ]
