# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181129_1709'),
        ('user', '0004_user_is_inspector'),
    ]

    operations = [
    ]
