# Generated by Django 2.1.1 on 2018-09-28 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True, verbose_name='Заголовок')),
                ('color', base.fields.ColorField(blank=True, default='#FF0000', max_length=18, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория метки',
                'verbose_name_plural': 'Категории меток',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attach', models.FileField(blank=True, null=True, upload_to='attach/', verbose_name='Прикрепленный файл')),
                ('name', models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='Имя не может содержать цифры', regex='^[a-zA-Zа-яА-Я\\s]+$')], verbose_name='ФИО')),
                ('phone', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Должно содержать только цифры, проблел и символы -.,()', regex='^[0-9-.,+\\s()]+$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('point', models.CharField(max_length=64, unique=True, verbose_name='Точка на карте')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено админом')),
                ('decision', models.FileField(blank=True, null=True, upload_to='decision/', verbose_name='Решение')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания метки')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='label.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
            },
        ),
    ]
