# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='attach',
            field=models.ImageField(blank=True, null=True, upload_to='attach/', verbose_name='Прикрепленный файл'),
        ),
    ]
