# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 16:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20181009_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='labels/')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.Label')),
            ],
        ),
    ]
