# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20181207_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ImageField(upload_to='decision/', verbose_name='Решение')),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='decision',
        ),
        migrations.AddField(
            model_name='decision',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.Label'),
        ),
    ]
