# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Местоположение'),
        ),
    ]
