# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 17:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_label_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('submit_date', models.DateTimeField(auto_now=True, verbose_name='Дата/время отправки')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='label.Label', verbose_name='Метка на карте')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-submit_date',),
            },
        ),
    ]
