# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='in_top',
            field=models.BooleanField(default=False, verbose_name='Вывести в топ'),
        ),
    ]
