# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_auto_20181128_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='attach',
        ),
    ]
